/**
 * 健澜科技数智医院智能体
 * Copyright (c) 2026 健澜科技. All rights reserved.
 *
 * 本文件为健澜科技专有技术文件，未经授权不得复制、传播或用于其他用途。
 *
 * CDS 诊疗规范符合度规则库
 * ---------------------------------------------------------------------------
 * 覆盖诊断支持度、治疗与诊断匹配、检查适应症、危险信号（红旗）识别。
 * 规则来源：中华医学会诊疗指南、国家临床路径、单病种质控标准。
 * 所有建议仅供医生参考，不替代临床判断。
 */

import type { CdsRule, ConditionNode } from '../Rule.js';
import { and, labGt, labLt, listAny } from './conditionHelpers.js';

/** 诊疗规范符合度规则 */
export const diagnosisRules: readonly CdsRule[] = [
  {
    id: 'COMP-DX-001',
    name: '呼吸道感染征象提示肺炎',
    description: '发热伴咳嗽、白细胞升高，提示下呼吸道感染，建议完善胸部影像',
    ruleType: 'diagnostic_compliance',
    version: '1.0.0',
    status: 'enabled',
    priority: 50,
    triggerEvents: ['record_write', 'manual'],
    tags: ['肺炎', '鉴别诊断', '红旗'],
    condition: and(listAny('symptoms', '发热'), listAny('symptoms', '咳嗽'), labGt('白细胞', 10)),
    action: {
      actionType: 'suggest',
      level: 'info',
      title: '诊疗建议：疑似下呼吸道感染',
      message:
        '患者症状{{symptoms}}，白细胞{{lab.白细胞}}，符合社区获得性肺炎表现，建议完善胸部影像。',
      suggestions: [
        '完善胸部CT/胸片明确病变范围',
        '评估CURB-65评分决定门诊/住院',
        '留取痰培养后经验性抗感染',
      ],
      requireOverride: false,
      evidence: [{ source: '社区获得性肺炎诊断和治疗指南', version: '2016' }],
    },
  },
  {
    id: 'COMP-DX-002',
    name: '腹痛黄疸提示胆道疾病',
    description: '右上腹痛伴黄疸/发热，提示急性胆道感染',
    ruleType: 'diagnostic_compliance',
    version: '1.0.0',
    status: 'enabled',
    priority: 55,
    triggerEvents: ['record_write', 'manual'],
    tags: ['胆道感染', '腹痛', '鉴别诊断'],
    condition: and(listAny('symptoms', '腹痛'), listAny('symptoms', '黄疸')),
    action: {
      actionType: 'suggest',
      level: 'warning',
      title: '诊疗建议：疑似胆道疾病',
      message: '患者症状{{symptoms}}，需警惕急性胆管炎/胆石症，建议尽快腹部超声与肝功能评估。',
      suggestions: [
        '急查肝功能、胆红素、淀粉酶',
        '腹部超声评估胆管扩张/结石',
        '外科会诊评估内镜/手术指征',
      ],
      requireOverride: false,
      evidence: [{ source: '急性胆道系统感染诊疗指南', version: '2021' }],
    },
  },
  {
    id: 'COMP-DX-003',
    name: '红旗信号：颅内高压征象',
    description: '突发剧烈头痛伴喷射性呕吐/血压升高，警惕颅内出血/占位',
    ruleType: 'diagnostic_compliance',
    version: '1.0.0',
    status: 'enabled',
    priority: 80,
    triggerEvents: ['record_write', 'manual'],
    tags: ['头痛', '红旗', '颅内高压'],
    condition: and(
      listAny('symptoms', '头痛'),
      listAny('signs', '呕吐'),
      listAny('signs', '高血压'),
    ),
    action: {
      actionType: 'warning',
      level: 'critical',
      title: '红旗信号：疑似颅内高压',
      message: '患者症状{{symptoms}}、体征{{signs}}，需警惕蛛网膜下腔出血/颅内占位。',
      suggestions: ['立即头颅CT平扫', '神经科急会诊', '密切监测意识、瞳孔与生命体征'],
      requireOverride: false,
      evidence: [{ source: '中国蛛网膜下腔出血诊治指南', version: '2022' }],
    },
  },
  {
    id: 'COMP-DX-004',
    name: '糖尿病血糖控制不佳提示',
    description: '已诊断2型糖尿病但糖化血红蛋白显著升高，提示控糖不达标',
    ruleType: 'diagnostic_compliance',
    version: '1.0.0',
    status: 'enabled',
    priority: 40,
    triggerEvents: ['record_write', 'manual'],
    tags: ['糖尿病', '随访'],
    condition: and(listAny('diagnoses', '糖尿病'), labGt('糖化血红蛋白', 9)),
    action: {
      actionType: 'suggest',
      level: 'info',
      title: '随访建议：血糖控制不达标',
      message: '患者诊断{{diagnoses}}，糖化血红蛋白{{lab.糖化血红蛋白}}%，提示近3月血糖控制不佳。',
      suggestions: [
        '评估用药依从性与饮食运动',
        '必要时调整降糖方案/加用胰岛素',
        '筛查糖尿病并发症（肾、眼底、神经）',
      ],
      requireOverride: false,
      evidence: [{ source: '中国2型糖尿病防治指南', version: '2024' }],
    },
  },
  {
    id: 'COMP-DX-005',
    name: '贫血需完善铁代谢检查',
    description: '血红蛋白降低时，建议完善铁代谢指标明确病因',
    ruleType: 'diagnostic_compliance',
    version: '1.0.0',
    status: 'enabled',
    priority: 35,
    triggerEvents: ['record_write', 'manual'],
    tags: ['贫血', '检查适应症'],
    condition: labLt('血红蛋白', 100),
    action: {
      actionType: 'suggest',
      level: 'info',
      title: '检查建议：贫血病因学检查',
      message: '血红蛋白{{lab.血红蛋白}} g/L，存在贫血，建议完善病因学检查。',
      suggestions: [
        '查铁蛋白、血清铁、总铁结合力',
        '查网织红细胞计数',
        '必要时外周血涂片/骨髓检查',
      ],
      requireOverride: false,
      evidence: [{ source: '贫血诊断与治疗中国专家共识', version: '2022' }],
    },
  },
  {
    id: 'COMP-DX-006',
    name: '粒细胞缺乏伴发热紧急预警',
    description: '白细胞极低伴发热，为粒缺性发热，属急症',
    ruleType: 'diagnostic_compliance',
    version: '1.0.0',
    status: 'enabled',
    priority: 90,
    triggerEvents: ['record_write', 'manual', 'lab_result_report'],
    tags: ['粒缺发热', '急症', '红旗'],
    condition: and(listAny('symptoms', '发热'), labLt('白细胞', 1.0)),
    action: {
      actionType: 'block',
      level: 'critical',
      title: '急症：粒细胞缺乏伴发热',
      message: '患者发热且白细胞{{lab.白细胞}}×10^9/L，为粒缺性发热，可迅速进展为脓毒症。',
      suggestions: ['1小时内启动经验性广谱抗生素', '保护性隔离、血培养', '联系血液科与ICU评估'],
      requireOverride: false,
      evidence: [{ source: '肿瘤化疗所致中性粒细胞减少伴发热防治指南', version: '2023' }],
    },
  },
  {
    id: 'COMP-DX-007',
    name: '急腹症建议外科评估',
    description: '转移性右下腹痛/腹膜刺激征提示急腹症，建议外科会诊',
    ruleType: 'diagnostic_compliance',
    version: '1.0.0',
    status: 'enabled',
    priority: 65,
    triggerEvents: ['record_write', 'manual'],
    tags: ['急腹症', '外科会诊'],
    condition: and(listAny('symptoms', '腹痛'), listAny('signs', '腹膜刺激')),
    action: {
      actionType: 'suggest',
      level: 'warning',
      title: '诊疗建议：疑似急腹症',
      message: '患者腹痛伴腹膜刺激征，需警惕消化道穿孔/阑尾炎等外科急腹症。',
      suggestions: ['外科急会诊', '腹部立位片/CT评估', '禁食禁水、做好术前准备'],
      requireOverride: false,
      evidence: [{ source: '急腹症腹腔镜探查中国专家共识', version: '2022' }],
    },
  },
  {
    id: 'COMP-DX-008',
    name: '治疗与诊断匹配：心衰建议利尿',
    description: '诊断心力衰竭者，建议评估容量状态并予规范药物',
    ruleType: 'diagnostic_compliance',
    version: '1.0.0',
    status: 'enabled',
    priority: 30,
    triggerEvents: ['record_write', 'manual'],
    tags: ['心力衰竭', '治疗匹配'],
    condition: listAny('diagnoses', '心力衰竭'),
    action: {
      actionType: 'suggest',
      level: 'info',
      title: '治疗建议：心衰规范用药',
      message: '患者诊断{{diagnoses}}，建议按指南评估并启动“新四联”规范治疗。',
      suggestions: [
        '评估容量负荷，必要时利尿',
        '启动ARNI/β阻滞剂/MRA/SGLT2i（新四联）',
        '监测体重、出入量与BNP',
      ],
      requireOverride: false,
      evidence: [{ source: '中国心力衰竭诊断和治疗指南', version: '2024' }],
    },
  },
  {
    id: 'COMP-DX-009',
    name: '胸痛三联排查建议',
    description: '主诉胸痛者，建议完善心电图、肌钙蛋白、D-二聚体等鉴别',
    ruleType: 'diagnostic_compliance',
    version: '1.0.0',
    status: 'enabled',
    priority: 45,
    triggerEvents: ['record_write', 'manual'],
    tags: ['胸痛', '鉴别诊断', '检查适应症'],
    condition: listAny('symptoms', '胸痛'),
    action: {
      actionType: 'suggest',
      level: 'warning',
      title: '检查建议：胸痛鉴别排查',
      message: '患者主诉胸痛，需鉴别急性冠脉综合征、主动脉夹层、肺栓塞等致命病因。',
      suggestions: ['12导联心电图', '肌钙蛋白、D-二聚体、BNP', '必要时主动脉/肺动脉CTA'],
      requireOverride: false,
      evidence: [{ source: '胸痛中心建设标准', version: '2023' }],
    },
  },
  {
    id: 'COMP-DX-010',
    name: '新生儿/儿童发热红旗',
    description: '3月龄以下婴儿伴发热，属高危，建议立即评估',
    ruleType: 'diagnostic_compliance',
    version: '1.0.0',
    status: 'enabled',
    priority: 85,
    triggerEvents: ['record_write', 'manual'],
    tags: ['儿童', '发热', '红旗'],
    condition: and(leafAgeLt90(), listAny('symptoms', '发热')),
    action: {
      actionType: 'warning',
      level: 'critical',
      title: '红旗信号：小婴儿发热',
      message: '患儿年龄<3月龄且伴发热，为严重细菌感染高危人群。',
      suggestions: [
        '立即儿科/急诊评估',
        '完善血尿常规、CRP、PCT、血培养',
        '谨慎经验性抗感染，勿随意退热',
      ],
      requireOverride: false,
      evidence: [{ source: '中国0至5岁儿童病因不明急性发热诊断指南', version: '2021' }],
    },
  },
  {
    id: 'COMP-DX-011',
    name: '晕厥建议心血管与神经系统评估',
    description: '晕厥发作需鉴别心源性与神经源性',
    ruleType: 'diagnostic_compliance',
    version: '1.0.0',
    status: 'enabled',
    priority: 40,
    triggerEvents: ['record_write', 'manual'],
    tags: ['晕厥', '鉴别诊断'],
    condition: listAny('symptoms', '晕厥'),
    action: {
      actionType: 'suggest',
      level: 'info',
      title: '检查建议：晕厥病因排查',
      message: '患者出现晕厥，需鉴别心源性（心律失常）与神经源性病因。',
      suggestions: ['12导联心电图、动态心电图', '卧立位血压', '必要时直立倾斜试验/头颅影像'],
      requireOverride: false,
      evidence: [{ source: '晕厥诊断与处理中国专家共识', version: '2023' }],
    },
  },
];

/** 辅助：年龄 < 90 天（约3月龄）的叶子条件 */
function leafAgeLt90(): ConditionNode {
  // facts.age 以岁为单位，< 0.25 岁即 < 约3月龄
  return { kind: 'leaf', field: 'age', operator: 'lt', value: 0.25 };
}
