/**
 * 健澜科技数智医院智能体
 * Copyright (c) 2026 健澜科技. All rights reserved.
 *
 * 本文件为健澜科技专有技术文件，未经授权不得复制、传播或用于其他用途。
 *
 * CDS 药物相关规则库
 * ---------------------------------------------------------------------------
 * 覆盖药物相互作用（DDI）、药物过敏（ALL）、剂量/特殊人群（DOSE）、
 * 禁忌症（CONTRA）与重复用药。阈值与分级参考国家药品说明书、中华医学会
 * 用药指南及《临床检验危急值报告制度》相关要求。所有结果仅供医生参考。
 */

import type { CdsRule } from '../Rule.js';
import { and, leaf, listAny, or } from './conditionHelpers.js';

// ============================================================================
// 规则集合
// ============================================================================

/** 药物相关规则（DDI / ALL / DOSE / CONTRA） */
export const drugRules: readonly CdsRule[] = [
  // ------------------------------------------------------------------ DDI
  {
    id: 'DDI-001',
    name: '华法林与抗血小板药联用出血风险',
    description: '华法林与阿司匹林/氯吡格雷联用显著增加消化道及颅内出血风险',
    ruleType: 'drug_interaction',
    version: '1.1.0',
    status: 'enabled',
    priority: 90,
    triggerEvents: ['order_create', 'prescription_create'],
    tags: ['华法林', '阿司匹林', '出血', 'DDI'],
    mutualExclusionGroup: 'bleeding-anti-coag',
    condition: and(
      listAny('currentDrugs', '华法林'),
      or(listAny('newDrugs', '阿司匹林'), listAny('newDrugs', '氯吡格雷')),
    ),
    action: {
      actionType: 'warning',
      level: 'critical',
      title: '严重药物相互作用：抗凝+抗血小板',
      message:
        '患者当前在用{{currentDrugs}}，新开{{newDrugs}}可能显著增加出血风险（华法林联合抗血小板药）。',
      suggestions: [
        '评估出血风险（HAS-BLED评分）',
        '如确需联用建议加用质子泵抑制剂',
        '密切监测INR与出血征象',
      ],
      requireOverride: false,
      overrideReasons: ['机械瓣膜需桥接抗凝', 'MDT会诊确认需联用', '其他（请说明）'],
      evidence: [
        { source: '华法林钠片说明书', version: '2023版' },
        { source: '中国心房颤动患者卒中预防规范', version: '2024' },
      ],
    },
    author: '药学部',
    createdAt: '2026-01-15',
  },
  {
    id: 'DDI-002',
    name: '非甾体抗炎药重复使用',
    description: '两种非甾体抗炎药（NSAID）联用增加胃肠出血与肾损伤风险',
    ruleType: 'drug_interaction',
    version: '1.0.0',
    status: 'enabled',
    priority: 60,
    triggerEvents: ['order_create', 'prescription_create'],
    tags: ['NSAID', '重复用药', '胃肠出血'],
    condition: and(
      listAny('newDrugs', '布洛芬'),
      or(
        listAny('newDrugs', '双氯芬酸'),
        listAny('newDrugs', '萘普生'),
        listAny('currentDrugs', '双氯芬酸'),
        listAny('currentDrugs', '吲哚美辛'),
      ),
    ),
    action: {
      actionType: 'warning',
      level: 'warning',
      title: '重复用药：非甾体抗炎药联用',
      message: '新开{{newDrugs}}与既往NSAID存在重复用药，可增加胃肠道及肾脏不良反应。',
      suggestions: [
        '避免两种NSAID同时使用',
        '如必须联用请加用胃黏膜保护剂',
        '监测肾功能与消化道症状',
      ],
      requireOverride: false,
      evidence: [{ source: '非甾体抗炎药临床应用专家共识', version: '2023' }],
    },
  },
  {
    id: 'DDI-003',
    name: 'ACEI/ARB与保钾利尿剂致高钾血症',
    description: 'ACEI/ARB与螺内酯联用可致严重高钾血症',
    ruleType: 'drug_interaction',
    version: '1.0.0',
    status: 'enabled',
    priority: 70,
    triggerEvents: ['order_create', 'prescription_create'],
    tags: ['ACEI', 'ARB', '螺内酯', '高钾'],
    condition: and(
      or(
        listAny('currentDrugs', '依那普利'),
        listAny('currentDrugs', '缬沙坦'),
        listAny('currentDrugs', '氯沙坦'),
      ),
      listAny('newDrugs', '螺内酯'),
    ),
    action: {
      actionType: 'warning',
      level: 'critical',
      title: '高钾血症风险：ACEI/ARB + 螺内酯',
      message: '患者在用{{currentDrugs}}，新开螺内酯可协同升高血钾，存在严重高钾血症风险。',
      suggestions: [
        '用药后3~7天复查血钾与肌酐',
        '肾功能不全者需减量或避免联用',
        '出现乏力/心律失常立即就诊',
      ],
      requireOverride: false,
      evidence: [{ source: '心力衰竭合理用药指南', version: '2024' }],
    },
  },
  {
    id: 'DDI-004',
    name: '氟喹诺酮与二价阳离子螯合',
    description: '左氧氟沙星与含钙/镁抗酸药同服可显著降低吸收',
    ruleType: 'drug_interaction',
    version: '1.0.0',
    status: 'enabled',
    priority: 40,
    triggerEvents: ['order_create', 'prescription_create'],
    tags: ['左氧氟沙星', '抗酸药', '螯合'],
    condition: and(
      listAny('newDrugs', '左氧氟沙星'),
      or(listAny('currentDrugs', '碳酸钙'), listAny('currentDrugs', '铝碳酸镁')),
    ),
    action: {
      actionType: 'alert',
      level: 'warning',
      title: '吸收影响：氟喹诺酮与抗酸药',
      message: '左氧氟沙星与含钙/镁抗酸药可发生螯合，影响抗菌疗效。',
      suggestions: ['两药间隔至少2小时服用', '抗酸药于左氧氟沙星服用后2小时以上给药'],
      requireOverride: false,
      evidence: [{ source: '左氧氟沙星片说明书', version: '2023版' }],
    },
  },
  {
    id: 'DDI-005',
    name: '辛伐他汀与CYP3A4抑制剂致肌病',
    description: '辛伐他汀与克拉霉素/伊曲康唑联用增加横纹肌溶解风险',
    ruleType: 'drug_interaction',
    version: '1.0.0',
    status: 'enabled',
    priority: 75,
    triggerEvents: ['order_create', 'prescription_create'],
    tags: ['辛伐他汀', '克拉霉素', '横纹肌溶解'],
    condition: and(
      or(listAny('currentDrugs', '辛伐他汀'), listAny('currentDrugs', '阿托伐他汀')),
      or(listAny('newDrugs', '克拉霉素'), listAny('newDrugs', '伊曲康唑')),
    ),
    action: {
      actionType: 'block',
      level: 'critical',
      title: '禁忌合用：他汀 + 强CYP3A4抑制剂',
      message:
        '患者在用{{currentDrugs}}，新开{{newDrugs}}抑制CYP3A4，可致他汀血药浓度骤升、横纹肌溶解。',
      suggestions: [
        '停用克拉霉素期间暂停他汀或换用普伐他汀',
        '监测肌酸激酶与肌肉症状',
        '必要时调整为非CYP3A4代谢他汀',
      ],
      requireOverride: true,
      overrideReasons: ['短暂合用且密切监测', '替代抗菌药均不耐受', '其他（请说明）'],
      evidence: [{ source: '血脂异常防治指南', version: '2023' }],
    },
  },

  // ------------------------------------------------------------------ ALL
  {
    id: 'ALL-001',
    name: '青霉素过敏禁用青霉素类',
    description: '患者青霉素过敏，新开青霉素类药物存在严重过敏休克风险',
    ruleType: 'drug_allergy',
    version: '1.0.0',
    status: 'enabled',
    priority: 95,
    triggerEvents: ['order_create', 'prescription_create'],
    tags: ['青霉素', '过敏', '过敏性休克'],
    condition: and(
      listAny('allergies', '青霉素'),
      or(
        listAny('newDrugs', '青霉素'),
        listAny('newDrugs', '阿莫西林'),
        listAny('newDrugs', '氨苄西林'),
      ),
    ),
    action: {
      actionType: 'block',
      level: 'critical',
      title: '用药禁忌：青霉素过敏',
      message: '患者过敏史为{{allergies}}，新开{{newDrugs}}属青霉素类，存在过敏性休克风险。',
      suggestions: [
        '换用非β-内酰胺类抗菌药',
        '如确需使用，须皮试并备好抢救措施',
        '在病历中记录过敏标识',
      ],
      requireOverride: true,
      overrideReasons: ['已评估获益大于风险并充分告知', '皮试阴性后谨慎使用', '其他（请说明）'],
      evidence: [{ source: '青霉素皮肤试验专家共识', version: '2022' }],
    },
  },
  {
    id: 'ALL-002',
    name: '青霉素过敏与头孢类交叉过敏',
    description: '青霉素过敏者使用头孢类需警惕交叉过敏',
    ruleType: 'drug_allergy',
    version: '1.0.0',
    status: 'enabled',
    priority: 65,
    triggerEvents: ['order_create', 'prescription_create'],
    tags: ['青霉素', '头孢', '交叉过敏'],
    condition: and(
      listAny('allergies', '青霉素'),
      or(
        listAny('newDrugs', '头孢'),
        listAny('newDrugs', '头孢曲松'),
        listAny('newDrugs', '头孢呋辛'),
      ),
    ),
    action: {
      actionType: 'warning',
      level: 'warning',
      title: '交叉过敏风险：青霉素 → 头孢类',
      message: '患者对{{allergies}}过敏，新开{{newDrugs}}与青霉素存在约5%~10%交叉过敏风险。',
      suggestions: [
        '优先选择第三代头孢（交叉过敏率更低）',
        '首次给药后观察30分钟',
        '备好肾上腺素等急救药品',
      ],
      requireOverride: false,
      evidence: [{ source: 'β-内酰胺类抗菌药皮试与过敏管理专家共识', version: '2023' }],
    },
  },
  {
    id: 'ALL-003',
    name: '磺胺过敏禁用磺胺类与相关药物',
    description: '磺胺类过敏者禁用复方磺胺甲噁唑及塞来昔布等含磺胺结构药物',
    ruleType: 'drug_allergy',
    version: '1.0.0',
    status: 'enabled',
    priority: 85,
    triggerEvents: ['order_create', 'prescription_create'],
    tags: ['磺胺', '过敏'],
    condition: and(
      listAny('allergies', '磺胺'),
      or(
        listAny('newDrugs', '磺胺甲噁唑'),
        listAny('newDrugs', '复方新诺明'),
        listAny('newDrugs', '塞来昔布'),
      ),
    ),
    action: {
      actionType: 'block',
      level: 'critical',
      title: '用药禁忌：磺胺过敏',
      message:
        '患者过敏史为{{allergies}}，新开{{newDrugs}}含磺胺结构，可诱发严重皮疹甚至Stevens-Johnson综合征。',
      suggestions: ['换用非磺胺类替代药物', '告知患者避免自行服用含磺胺成分药物'],
      requireOverride: true,
      overrideReasons: ['确无替代药物并充分知情', '其他（请说明）'],
      evidence: [{ source: '药物过敏反应规范化处置专家共识', version: '2023' }],
    },
  },

  // ------------------------------------------------------------------ DOSE / 特殊人群
  {
    id: 'DOSE-001',
    name: '儿童禁用氟喹诺酮类',
    description: '18岁以下使用氟喹诺酮可损伤软骨发育',
    ruleType: 'dose_anomaly',
    version: '1.0.0',
    status: 'enabled',
    priority: 88,
    triggerEvents: ['order_create', 'prescription_create'],
    tags: ['儿童', '氟喹诺酮', '软骨'],
    condition: and(
      leaf('age', 'lt', 18),
      or(
        listAny('newDrugs', '左氧氟沙星'),
        listAny('newDrugs', '环丙沙星'),
        listAny('newDrugs', '莫西沙星'),
      ),
    ),
    action: {
      actionType: 'block',
      level: 'critical',
      title: '年龄禁忌：儿童禁用氟喹诺酮',
      message: '患者年龄{{age}}岁（<18岁），新开{{newDrugs}}为氟喹诺酮类，可能影响软骨发育。',
      suggestions: ['换用青霉素类/头孢类等儿童安全抗菌药', '如确需使用须经儿童专科会诊'],
      requireOverride: true,
      overrideReasons: ['多重耐药且无替代', '儿科会诊同意', '其他（请说明）'],
      evidence: [{ source: '抗菌药物临床应用指导原则', version: '2015版' }],
    },
  },
  {
    id: 'DOSE-002',
    name: '肾功能不全需调整剂量',
    description: '严重肾功能不全使用经肾排泄药物需减量',
    ruleType: 'dose_anomaly',
    version: '1.0.0',
    status: 'enabled',
    priority: 70,
    triggerEvents: ['order_create', 'prescription_create'],
    tags: ['肾功能不全', '剂量调整', '万古霉素', '二甲双胍'],
    condition: and(
      leaf('renalBand', 'equals', 'severe'),
      or(listAny('newDrugs', '万古霉素'), listAny('newDrugs', '二甲双胍')),
    ),
    action: {
      actionType: 'warning',
      level: 'critical',
      title: '肾功能不全：剂量需调整',
      message: '患者肾功能分级为重度，新开{{newDrugs}}主要经肾排泄，蓄积可致毒性。',
      suggestions: [
        '按eGFR计算调整剂量并延长给药间隔',
        '二甲双胍在严重肾功能不全应停用',
        '必要时血药浓度监测（万古霉素）',
      ],
      requireOverride: false,
      evidence: [{ source: '肾功能不全患者用药专家共识', version: '2023' }],
    },
  },
  {
    id: 'DOSE-003',
    name: '老年多重用药提醒',
    description: '≥75岁患者多药联用需警惕跌倒与中枢抑制',
    ruleType: 'dose_anomaly',
    version: '1.0.0',
    status: 'enabled',
    priority: 45,
    triggerEvents: ['order_create', 'prescription_create'],
    tags: ['老年', '多重用药', '跌倒'],
    condition: and(leaf('age', 'gte', 75), listAny('newDrugs', '地西泮')),
    action: {
      actionType: 'alert',
      level: 'warning',
      title: '老年用药安全：苯二氮䓬类',
      message: '患者{{age}}岁，新开地西泮可增加老年人跌倒、谵妄风险（Beers标准不推荐）。',
      suggestions: ['优先选用非药物助眠方案', '如必须使用宜短效、低剂量、短疗程'],
      requireOverride: false,
      evidence: [{ source: 'Beers老年人潜在不适当用药标准', version: '2023' }],
    },
  },

  // ------------------------------------------------------------------ CONTRA
  {
    id: 'CONTRA-001',
    name: '妊娠禁忌：ACEI/ARB/喹诺酮/四环素',
    description: '妊娠期使用肾素-血管紧张素系统药物或喹诺酮/四环素可致畸',
    ruleType: 'contraindication',
    version: '1.0.0',
    status: 'enabled',
    priority: 96,
    triggerEvents: ['order_create', 'prescription_create'],
    tags: ['妊娠', '致畸', 'ACEI', 'ARB'],
    condition: and(
      leaf('pregnant', 'equals', true),
      or(
        listAny('newDrugs', '依那普利'),
        listAny('newDrugs', '缬沙坦'),
        listAny('newDrugs', '左氧氟沙星'),
        listAny('newDrugs', '四环素'),
      ),
    ),
    action: {
      actionType: 'block',
      level: 'critical',
      title: '妊娠禁忌用药',
      message: '患者为妊娠期，新开{{newDrugs}}为妊娠期禁忌（致畸或影响胎儿发育）。',
      suggestions: ['换用妊娠安全分级更高的替代药物', '用药前请产科会诊并记录知情同意'],
      requireOverride: true,
      overrideReasons: ['危及母体生命需使用', '产科会诊确认获益', '其他（请说明）'],
      evidence: [{ source: '妊娠期用药指南', version: '2023' }],
    },
  },
  {
    id: 'CONTRA-002',
    name: '妊娠禁忌：华法林',
    description: '华法林可通过胎盘致胎儿华法林综合征',
    ruleType: 'contraindication',
    version: '1.0.0',
    status: 'enabled',
    priority: 96,
    triggerEvents: ['order_create', 'prescription_create'],
    tags: ['妊娠', '华法林'],
    condition: and(leaf('pregnant', 'equals', true), listAny('newDrugs', '华法林')),
    action: {
      actionType: 'block',
      level: 'critical',
      title: '妊娠禁忌：华法林',
      message: '妊娠期使用华法林可致胎儿华法林综合征、中枢神经系统异常及出血。',
      suggestions: ['妊娠期抗凝优先选用低分子肝素', '多学科评估抗凝指征与孕周'],
      requireOverride: true,
      overrideReasons: ['机械瓣膜需抗凝且无替代', '其他（请说明）'],
      evidence: [{ source: '妊娠合并抗凝治疗专家共识', version: '2022' }],
    },
  },
  {
    id: 'CONTRA-003',
    name: '活动性消化性溃疡禁用NSAID',
    description: '活动性消化性溃疡患者使用NSAID可诱发消化道大出血',
    ruleType: 'contraindication',
    version: '1.0.0',
    status: 'enabled',
    priority: 82,
    triggerEvents: ['order_create', 'prescription_create'],
    tags: ['消化性溃疡', 'NSAID', '消化道出血'],
    condition: and(
      listAny('diagnoses', '溃疡'),
      or(
        listAny('newDrugs', '布洛芬'),
        listAny('newDrugs', '双氯芬酸'),
        listAny('newDrugs', '吲哚美辛'),
      ),
    ),
    action: {
      actionType: 'block',
      level: 'critical',
      title: '疾病禁忌：活动性溃疡禁用NSAID',
      message: '患者诊断为{{diagnoses}}，新开{{newDrugs}}可诱发溃疡出血或穿孔。',
      suggestions: ['镇痛优先选用对乙酰氨基酚', '如必须使用需质子泵抑制剂保护并密切随访'],
      requireOverride: true,
      overrideReasons: ['已规范抑酸治疗', '获益大于风险并充分告知', '其他（请说明）'],
      evidence: [{ source: '消化性溃疡诊疗指南', version: '2022' }],
    },
  },
  {
    id: 'CONTRA-004',
    name: '哮喘禁用非选择性β受体阻滞剂',
    description: '支气管哮喘患者使用普萘洛尔可诱发支气管痉挛',
    ruleType: 'contraindication',
    version: '1.0.0',
    status: 'enabled',
    priority: 80,
    triggerEvents: ['order_create', 'prescription_create'],
    tags: ['哮喘', 'β受体阻滞剂'],
    condition: and(listAny('diagnoses', '哮喘'), listAny('newDrugs', '普萘洛尔')),
    action: {
      actionType: 'block',
      level: 'critical',
      title: '疾病禁忌：哮喘患者禁用普萘洛尔',
      message: '患者诊断{{diagnoses}}，普萘洛尔为非选择性β受体阻滞剂，可诱发严重支气管痉挛。',
      suggestions: ['如需β阻滞剂宜选高选择性β1受体阻滞剂（如美托洛尔）', '呼吸科会诊评估'],
      requireOverride: true,
      overrideReasons: ['其他降压/抗心律失常药物均不耐受', '其他（请说明）'],
      evidence: [{ source: '支气管哮喘防治指南', version: '2020' }],
    },
  },
  {
    id: 'CONTRA-005',
    name: '严重肾功能不全禁用含碘造影剂',
    description: '严重肾功能不全患者增强CT使用碘造影剂可致造影剂肾病',
    ruleType: 'contraindication',
    version: '1.0.0',
    status: 'enabled',
    priority: 78,
    triggerEvents: ['check_request', 'order_create'],
    tags: ['造影剂', '造影剂肾病', '肾功能不全'],
    condition: and(leaf('renalBand', 'equals', 'severe'), listAny('newDrugs', '碘造影剂')),
    action: {
      actionType: 'warning',
      level: 'critical',
      title: '相对禁忌：重度肾功能不全使用碘造影剂',
      message: '患者肾功能重度受损，行增强CT使用碘造影剂存在造影剂肾病风险。',
      suggestions: ['检查前后充分水化', '评估可否用MRI等替代', '检查后48~72小时复查肌酐'],
      requireOverride: false,
      evidence: [{ source: '造影剂肾病预防中国专家共识', version: '2023' }],
    },
  },
];
