{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jlmedaios.secretName" . }}
  namespace: {{ include "jlmedaios.namespace" . }}
  labels:
    {{- include "jlmedaios.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secret.postgresUser | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.secret.redisPassword | b64enc | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | b64enc | quote }}
  ENCRYPTION_MASTER_KEY: {{ .Values.secret.encryptionMasterKey | b64enc | quote }}
{{- end -}}
